# -*- coding: utf-8 -*-
"""client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_H2kzp7a4nite4hJMKS8fhoM6FWFU-5
"""

import socket

s = socket.socket()
port = 3125
s.connect(('localhost', port))
z = 'Welcome to Manipal'
s.sendall(z.encode())    
s.close()